#Geoip data
#Reminder: use spaces, yaml doesn't allow tabs
geoip:
    geoippath: Geolite
    geoipasnfilename: Geolite2-ASN.mmdb
    geoipcountryfilename: Geolite2-Country.mmdb
    geoipupdatescript: UpdateGeoliteDatabases.sh
    geoiplicensekey: TpCPFWiVfktxfdEp

# Database configurations
database:
    dbname: observatorio
    dbuser: obslac
    dbpass: password
    dbhost: 172.21.128.1
    dbport: 5432

#runing arguments
runargs:
    inputfilepath: input-example.txt
    dontprobefilepath: dontprobefile.txt
    concurrency: 100
    ccmax: 100
    maxretry: 2
    dropdatabase: false
    debug: false
    dnsservers: ["8.8.8.8"]
#End of config data